### ISSUE TITLE
Decide which administrative category Key belongs to

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#24]
Currently the admin page for managing keys can be found under Structure, but the path suggests that it's under Configuration (/admin/config/system/key). We should choose one or the other and be consistent.

**Comment by rlhawk** [comment]
I could go either way (Structure or Configuration), but Configuration seems to make a bit more sense.

**Comment by nerdstein** [comment]
Configuration is fine for me.

Do you want to handle this?

**Comment by nerdstein** [comment]
Fixed this...

PR: https://github.com/d8-contrib-modules/key/pull/31
