### ISSUE TITLE
Make route paths for key management conform to Drupal standard

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#28]
The current paths for key management look like this:

- /admin/config/system/key
- /admin/config/system/key/add
- /admin/config/system/key/{key}
- /admin/config/system/key/{key}/delete

Consider a situation where a user creates a key with a machine name of 'add'. They would never be able to edit it (though they could delete it).

We should modify the paths to match the standard Drupal pattern for paths, as follows:

- /admin/config/system/key
- /admin/config/system/key/add
- /admin/config/system/key/manage/{key}
- /admin/config/system/key/manage/{key}/delete

**Comment by nerdstein** [comment]
@rlhawk - close?

**Comment by nerdstein** [comment]
PR: https://github.com/d8-contrib-modules/key/pull/31

Closing
