### ISSUE TITLE
Add a plugin type to allow types of keys to be defined

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#3]
Currently, the Key Type plugin type seems to be defining what is called "Key Storage Method" in the Drupal 7 version of Key and called "Key Provider" in the Drupal 7 version of Encrypt. Key Type should actually indicate the type of key being defined. For example, a module could define a key type of "Authorize.net Transaction Key," which would allow for validation rules specific to that type of key and would allow filtering of the list of keys by modules that use them. We will need a new plugin type to add storage-method functionality. I'll create a separate issue for that.

**Comment by nerdstein** [comment]
Please see my comment on the other ticket. Per the "validation" request, this should be handled through the standard validation routine baked into the settings form mentioned in the other ticket.

If this meets your needs, please close the ticket or elaborate further.

**Comment by rlhawk** [comment]
I added my comments in the other issue and have changed the title of this one. This functionality is not critical, but it would be an enhancement to the module if it can be added at some point.

**Comment by nerdstein** [comment]
This PR should address the core of the concern: https://github.com/d8-contrib-modules/key/pull/18

**Comment by nerdstein** [comment]
Add a taxonomy and tags to Key. Add tag filter as a new service endpoint to return keys of specific tag

**Comment by nerdstein** [comment]
Another alternative: add a field to the Key entity for the number of bits

**Comment by nerdstein** [comment]
Closing this issue and revisiting later
