### ISSUE TITLE
Provide a better message when no keys are available

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#34]
When there are no keys to list on the Key Manager page, the default Drupal no-results text (“There is no Key yet.”) is displayed, which is awkward. It should be changed to something similar to what Taxonomy provides (“No vocabularies available. Add vocabulary.”).

**Comment by nerdstein** [comment]
This seems reasonable.

something like, "No keys are available. Add Key." where "Add Key" is a link to the form?

**Comment by rlhawk** [comment]
Yes. There's a pull request for this, but it was suggested to add a test for it.

**Comment by rlhawk** [comment]
This has been committed.
