### ISSUE TITLE
Change HTML field label for key label field

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#36]
Sorry for the confusing issue title.

A standard Drupal pattern when referring to an item’s (user-friendly) label in a form is to use the term “name”. See examples below. We should change “Label” to “Key name” to be consistent with this pattern.

![image](https://cloud.githubusercontent.com/assets/851084/9179962/a635309c-3f54-11e5-96c0-293fbf096db6.png)
![image](https://cloud.githubusercontent.com/assets/851084/9179989/d7c6c7a6-3f54-11e5-9d6c-111ba6b7f9cf.png)
![image](https://cloud.githubusercontent.com/assets/851084/9180047/2b6f2a38-3f55-11e5-8e2b-04d07b92f295.png)

**Comment by nerdstein** [comment]
Cool, sounds good to me.

**Comment by nerdstein** [comment]
@rlhawk you got this?

**Comment by rlhawk** [comment]
Yep, already assigned.

**Comment by rlhawk** [comment]
This is in pull request #44.

**Comment by rlhawk** [comment]
This has been committed.
