### ISSUE TITLE
Submitting the key edit form without a key provider returns an error

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#37]
The #empty_value is set to 'none', which is interpreted to be a key name, rather than an empty value. It should be changed to an empty string (or just not defined), unless of course we want to allow 'none' to be a valid key provider. I guess that would allow you to create a dummy key that doesn't actually return anything. Do we want that?

**Comment by nerdstein** [comment]
Assigning @mjl3475 to eval

**Comment by mjl3475** [comment]
@rlhawk is right here. We should alter #empty_value to ''. I don't see any benefit to having a dummy key so long as we keep SimpleKey batched with the module.

I'll submit the PR.

**Comment by mjl3475** [comment]
https://github.com/d8-contrib-modules/key/pull/42

**Comment by rlhawk** [comment]
If we are going to have an empty value, we should change its label to set it off from the other options. Drupal core does that a couple of different ways, but I prefer the format used at /admin/config/search/pages for the Search Page Type field:

![image](https://cloud.githubusercontent.com/assets/851084/9390636/23e509a2-4727-11e5-93f1-805e9ac98a78.png)

So ours would be: 
```- Choose key provider -```
or 
```- Select key provider -```

**Comment by mjl3475** [comment]
Updated the PR

**Comment by mjl3475** [comment]
Merged
