### ISSUE TITLE
Improve key provider names

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#39]
The default key providers available have the following names:

- Simple key
- File key

"Key" in both instances is unnecessary and "Simple key" doesn't give a clear indication of how the key is actually being provided. I propose the following two replacement names:

- Drupal configuration
- File

**Comment by nerdstein** [comment]
So, this is using Drupal, right? "Drupal configuration" seems a bit repetitive. What about "Configuration"?

I also see "Configuration" being a bit ambiguous. This is "Text Configuration". I can also see examples of "File Configuration" or other config options we could potentially write. "File" may then be confusing. "Filesystem" seems more apt. 

Thoughts?

**Comment by rlhawk** [comment]
My thought was that "Configuration" wasn't specific enough and that we should be clear that it's using Drupal's configuration system. Maybe that's unnecessary.
