### ISSUE TITLE
Remove File provider's Method setting field

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#40]
The Method setting field for the File key provider is used to select a **transformation** that should happen to the contents of the file when the key is being retrieved. The result of the transformation is the key itself. The two available options are "file contents," which does no transformation, and "MD5 hash," which uses an MD5 hash of the file contents as the key. We should change the name of the field to better reflect its purpose—perhaps to "Transformation," "Process," "Modification"—something other than "Method," which is vague.

In addition, the File provider needs to have a new option for this field, "Base64 decode," which should base64 decode the contents of the file and use that as the key. The Drupal configuration (Simple key) provider also needs to have this field as a setting, with "Base64 decode" as an option, but I will create a separate issue for that.

**Comment by rlhawk** [comment]
I thought about this more and came to the conclusion that we should drop the Method field from the File key provider settings, unless someone can suggest a good reason why it should continue to exist. I suspect that it was originally added in Encrypt in an attempt to make the key the necessary length for the Rijndael-256 cipher, but it doesn't really do that. Even though the result is a 32-character string, it is essentially a 128-bit key, and we aren't doing users any favors by leading them to believe their keys are stronger than they are. In addition, by failing to perform key stretching and not using a salt, the functionality makes a key vulnerable to a rainbow table attack.

I propose that we remove the field from the key provider settings and add a new checkbox field, available for all providers, to indicate that the key is Base64-encoded. That's the only transformation I can think of that should be supported.

**Comment by nerdstein** [comment]
@mjl3475 - where did the method field for the File plugin come from originally?

I think we should try to understand what use case is that this resolves. If there is not a "clear" one. We can remove it. Or, we can create a separate plugin called `FilesystemMD5`.

@rlhawk - how do you envision base64 checkbox being used? I'm not clear on why/how that would be used and if this opens up new requirements for the service?

**Comment by mjl3475** [comment]
I believe it was also named "method" in the D7 version.

**Comment by rlhawk** [comment]
Yes, the settings field was called "method" in Encrypt for D7.

The only use case I can think of is to make a key the right length for a particular encryption algorithm, but it only pretends to do that (see below) and in an insecure manner, due to the lack of a salt.

Base64 decoding would mostly be useful for the configuration/simple method, so users can submit their key base64-encoded and it would be decoded properly when retrieved. It's possible that users would want to have their keys be in a readable format for any method, though, so it should be available for all. 

The feature wouldn't exist just for kicks though; it has real-world security implications. For example: with Rijndael-128, it's very important that the key be 128 bits of random data. If you were to generate a 16-character key by, say, truncating the results of a hash function like MD5, it would seem to fit that requirement. However, the keyspace would actually be reduced by a factor of 2^128. Using drupal_random_bytes(16)—or whatever the D8 replacement is—truly does produce 128 bits of random data, but it's not readable. Thus the need to base64-encode it, if you want it to be readable. But then Key needs to know to base64-decode it when retrieving it.

**Comment by rlhawk** [comment]
None of this matters, of course, for basic API keys, since they will always be readable.
