### ISSUE TITLE
Fix formatting of DocBlocks in KeyManager

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#49]
Shouldn't the DocBlocks for the methods in KeyManager.php have an extra asterisk in the first line to conform with DocBlock standards?

Current:
```
/*
 * Loading all keys.
 *
```
Proposed:
```
/**
 * Loading all keys.
 *
```

**Comment by pjonckiere** [comment]
Created a pull request here: https://github.com/d8-contrib-modules/key/pull/60
