### ISSUE TITLE
Move Key from Security section to System section on Configuration page

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#70]
From #33:

> I don't think it's possible for a contributed module to add a top-level administrative section, along with its own page, without causing complications and problems.

Problem 1: If multiple modules define the security section, multiple instances of it appear on the Configuration page.

![image](https://cloud.githubusercontent.com/assets/851084/10464032/9b652954-719c-11e5-9973-adec2008e571.png)

Problem 2: If multiple modules define the route to the security section's page, only one will be used. For example, if Key and Password Policy both define the path "/admin/config/security", only one of the module's admin pages will be listed on it. In my tests, it was Key, but I suppose it depends on the loading order of the modules.

![image](https://cloud.githubusercontent.com/assets/851084/10464193/5bd2c16a-719d-11e5-8211-6af4eabdab44.png)

I propose that the Keys admin link be moved under the System category, unless there's an easy way to resolve the problems introduced by defining the Security category.

**Comment by rlhawk** [comment]
My conclusion is that defining a new top-level section within Configuration has to be done once, either within core or in a contributed module. It seems clunky to have a separate module just to do that, then Key et al. would need to have it as a dependency.

Is there maybe some way to do logic within the YAML file, so the route and link could be checked and if they don't already exist, they could be created?

**Comment by rlhawk** [comment]
Does anyone have any new information about this? If not, I propose that we move Key from Security to the System by merging PR #71.

**Comment by nerdstein** [comment]
I think that is good for now - no news here

**Comment by rlhawk** [comment]
OK, merged.
