### ISSUE TITLE
Give key providers access to the key entity attributes

### ISSUE THREAD

**Issue by tynor** [d8-contrib-modules/key#72]
Use Case
---
Lockr (and possibly other external key providers) store metadata about keys in their own systems, which must be accessed by some ID. Reusing the key entity's ID simplifies that process and prevents the user being required to enter a separate ID for the service in addition to one for the entity itself.

It is possible to generate a random ID to satisfy that requirement. However, if an external key provider, like Lockr, aims to allow users to list and modify their keys directly in the external service, having the key names and descriptions match makes that process much easier.

Changes
---

(Breaks backwards compatibility.)

I propose to change `KeyProviderInterface::getKeyValue()`'s function signature from:

```php
public function getKeyValue();
```

to

```php
public function getKeyValue(KeyInterface $key);
```

and modify the configuration form such that it allows access to the key entity values from the key provider. Currently it only passes the 'key_settings' subset of form values.

Could be as simple as changing:

```php
$plugin_settings = (new FormState())->setValues($form_state->getValue('key_settings'));
$plugin = $this->manager->createInstance($form_state->getValue('key_provider'), []);
$plugin->submitConfigurationForm($form, $plugin_settings);
```
to

```php
$plugin = $this->manager->createInstance($form_state->getValue('key_provider'), []);
$plugin->submitConfigurationForm($form, $form_state);
```

as well as the respective change for `KeyForm::validateForm()`.

Another option would be to not change `KeyProviderInterface::getKeyValue()` and leave it up to the key provider to store relevant data from the key in `KeyProviderBase::submitConfigurationForm()`. Though this sounds like storing redundant information since I can't think of a reason one would change the key entity without wanting the provider to update.

If there is an alternative that makes sense and maintains backwards compatibility, I would love to hear it.

**Comment by tynor** [comment]
@rlhawk Thoughts?

**Comment by rlhawk** [comment]
Maintaining backward compatibility is not important at this point. I think your first suggestion makes sense.

**Comment by tynor** [comment]
Great, I will go ahead and implement.
