### ISSUE TITLE
Add ability for users to enable integration on a case-by-case basis

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#8]
The Drupal 7 version of Key requires a user to specifically enable integration with other modules that can use it. This gives the user more control over when Key is handling a key for another module, instead of just taking over everything it can when it's enabled. I think this is an useful feature and we should duplicate it in the Drupal 8 module. I'm open to suggestions for how to improve this functionality.

**Comment by nerdstein** [comment]
I think we have this covered..

1. Modules can make "key" a dependency to leverage Key concepts
2. KeyManager service is built into the Key module to invoke Key functionality from within another module
3. Key ships with common key providers, like file, config, etc
4. Modules can create their own KeyProviders for custom needs

**Comment by nerdstein** [comment]
@rlhawk - close?
