### ISSUE TITLE
Add baked in KeyType plugin for FileKey

### ISSUE THREAD

**Issue by mjl3475** [d8-contrib-modules/key#9]

**Comment by mjl3475** [comment]
Started in branch https://github.com/nerdstein/key/tree/Issue-9-Add-File-Key-Plugin . validation on the key add form doesn't seem to be triggering though.

@nerdstein, can you take a look when you get a chance.

**Comment by mjl3475** [comment]
https://github.com/nerdstein/key/blob/master/src/Form/KeyForm.php#L104-L106

**Comment by nerdstein** [comment]
Need to add validateForm into KeyForm and leverage same concepts found in lines 104 to 106 to trigger settings form validation within

**Comment by nerdstein** [comment]
@mjl3475 - current status?

**Comment by nerdstein** [comment]
Closed, Matt fixed the validation routine
